version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "80:80"
          - "8080:8080"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=laravel"
